// Habit icon mapping and resolver utility

export const HABIT_CATEGORIES = [
  { id: 'all', name: 'All' },
  { id: 'wellness', name: 'Wellness', icon: '🌿' },
  { id: 'fitness', name: 'Fitness', icon: '⚡' },
  { id: 'mind', name: 'Mindfulness', icon: '🧠' },
  { id: 'productivity', name: 'Productivity', icon: '🎯' },
  { id: 'routine', name: 'Daily Routine', icon: '☀️' },
]

export const HABIT_PRESETS = [
  { name: 'Drink 2L Water', detail: 'Stay hydrated throughout the day', icon: '💧', color: 'blue', category: 'wellness' },
  { name: 'Morning Sun & Walk', detail: '15 mins outdoors early morning', icon: '☀️', color: 'yellow', category: 'wellness' },
  { name: 'Read 20 Pages', detail: 'Feed the mind before sleeping', icon: '📖', color: 'lilac', category: 'mind' },
  { name: '10 min Meditation', detail: 'Center breath and clear mind', icon: '🧘', color: 'mint', category: 'mind' },
  { name: 'Exercise & Movement', detail: '30 mins workout or stretching', icon: '💪', color: 'peach', category: 'fitness' },
  { name: 'No Phone after 10 PM', detail: 'Deep sleep wind-down routine', icon: '📵', color: 'peach', category: 'routine' },
]

export const HABIT_ICON_MAP = {
  'Morning sun': '☀️',
  'Move my body': '💪',
  'Read': '📖',
  'No phone after 10': '📵',
  'Meditate': '🧘',
  'Journal': '📓',
  'Exercise': '🏃',
  'Water': '💧',
  'Stretch': '🤸',
  'Gratitude': '🙏',
  'Walk': '🚶',
  'Yoga': '🧘‍♀️',
  'Breathwork': '💨',
  'Sketch': '✏️',
  'Learn': '🎓',
  'Code': '💻',
  'Walk in nature': '🌳',
  'Dance': '💃',
  'Sing': '🎤',
  'Draw': '🎨',
  'Play': '🎮',
  'Cook': '👨‍🍳',
  'Bake': '🥖',
  'Garden': '🌱',
  'Plant': '🌿',
  'Clean': '🧹',
  'Tidy': '🧺',
  'Organize': '📦',
  'Plan': '📅',
  'Review': '👀',
  'Reflect': '🤔',
  'Visualize': '👁️',
  'Affirm': '✨',
  'Pray': '🙏',
  'Study': '📚',
  'Practice': '🎯',
  'Train': '🏋️',
  'Lift': '🏋️‍♀️',
  'Run': '🏃',
  'Bike': '🚴',
  'Swim': '🏊',
  'Hike': '🥾',
  'Climb': '🧗',
  'Mindfulness': '🧠',
  'Breath': '💨',
  'Flex': '💪',
  'Strength': '💪',
  'Power': '⚡',
  'Energy': '⚡',
  'Vitality': '💫',
  'Wellness': '🌿',
  'Health': '❤️',
  'Fitness': '🏋️',
  'Nutrition': '🥗',
  'Diet': '🥗',
  'Meal prep': '🥘',
  'Healthy eating': '🥑',
  'Sleep': '😴',
  'Rest': '😌',
  'Recovery': '🩹',
  'Healing': '🩹',
  'Therapy': '💆',
  'Massage': '💆',
  'Spa': '🧖',
  'Relax': '☕',
  'Chill': '😌',
  'Zen': '🪨',
  'Peace': '☮️',
  'Harmony': '🎵',
  'Balance': '⚖️',
  'Stability': '🧱',
  'Ground': '🌍',
  'Earth': '🌍',
  'Nature': '🌿',
  'Green': '💚',
  'Eco': '♻️',
  'Sustain': '🌱',
  'Grow': '🌱',
  'Flourish': '🌷',
  'Thrive': '📈',
  'Bloom': '🌸',
  'Flower': '🌺',
  'Leaf': '🍃',
  'Tree': '🌳',
  'Forest': '🌲',
  'Mountain': '⛰️',
  'Ocean': '🌊',
  'Wave': '🌊',
  'River': '🌊',
  'Lake': '💧',
  'Sky': '☁️',
  'Cloud': '☁️',
  'Star': '⭐',
  'Moon': '🌙',
  'Sun': '☀️',
  'Light': '💡',
  'Fire': '🔥',
  'Air': '💨',
  'Spirit': '✨',
  'Soul': '💫',
  'Heart': '❤️',
  'Mind': '🧠',
  'Body': '💪',
}

export function getIconForHabit(name) {
  if (!name || typeof name !== 'string') return '✨'
  const trimmed = name.trim()
  if (HABIT_ICON_MAP[trimmed]) return HABIT_ICON_MAP[trimmed]

  const lower = trimmed.toLowerCase()
  for (const [key, icon] of Object.entries(HABIT_ICON_MAP)) {
    if (lower.includes(key.toLowerCase())) {
      return icon
    }
  }

  return '✨'
}
